routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index');


Route::get('/games-alphabet/{char}', 'GameController@alphabet');
Route::get('/games/search', 'GameController@search');
Route::get('/games/search_more', 'GameController@search_more');

Route::get('/game/{bgg_id}', 'GameController@game');
Route::get('/game/{bgg_id}/{bgg_slug}', 'GameController@game');


Route::get('/login/facebook', 'Auth\LoginController@redirectToProvider');
Route::get('/login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

Route::group(['middleware' => ['auth']], function () {
    Route::post('/post/create/{game_id}/buy', 'GameController@post_buy');
    Route::post('/post/create/{game_id}/sell', 'GameController@post_sell');

    Route::post('/post/ajax', 'GameController@post_ajax');

});


//Route::get('/thumbnail/{file}', function()
//{
//
//    $img = Image::make('foo.jpg')->resize(300, 200);
//
//    return $img->response('jpg');
//});

app/Game.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;


/**
 * Class Game
 * @package App
 * @property string bgg_id
 * @property string bgg_slug
 * @property string bgg_name
 * @property float bgg_gbrank
 * @property float bgg_lcrank
 * @property float bgg_lcvote
 * @property string bgg_type
 * @property string bgg_image
 * @property integer bgg_year
 * @property integer bgg_own
 * @property float bgg_esw
 * @property float bgg_esh
 * @property float bgg_esl
 * @property float bgg_eswg
 * @property object bgg_last_update
 * @property integer mnmk_id
 * @property string mnmk_name
 * @property string mnmk_image
 * @property integer mnmk_stock
 * @property object mnmk_last_update
 * @property float mnmk_price
 * @property float mnmk_retail
 * @property string mnmk_url
 * @property string mnmk_code
 *
 *
 */
class Game extends Model
{

    protected $fillable = [
        'bgg_id',
        'bgg_slug',
        'bgg_name',
        'bgg_gbrank',
        'bgg_lcrank',
        'bgg_lcvote',
        'bgg_type',
        'bgg_image',
        'bgg_year',
        'bgg_own',
        'bgg_esw',
        'bgg_esh',
        'bgg_esl',
        'bgg_eswg',
        'bgg_last_update',
        'mnmk_id',
        'mnmk_name',
        'mnmk_image',
        'mnmk_stock',
        'mnmk_last_update',
        'mnmk_price',
        'mnmk_retail',
        'mnmk_url',
        'mnmk_code'
    ];


    static function cacheSearchByAlphabetQuery($char, $minutes = 60)
    {
        $value = null;
        if ($char == '0-9') {
            $value = Cache::remember('game::cacheSearchByAlphabetQuery(' . $char . ')', $minutes, function () {
                return Game::Query()->where('bgg_name', 'REGEXP', '^[0-9]')->orderBy('bgg_name')->get();
            });
        } else {
            $value = Cache::remember('game::cacheSearchByAlphabetQuery(' . $char . ')', $minutes, function () use ($char) {
                return Game::Query()->where('bgg_name', 'like', $char . '%')->orWhere('bgg_name', 'like', 'the ' . $char . '%')->orderBy('bgg_name')->get();
            });
        }
        return $value;
    }


    static function cacheSearchByKeywordQuery($keyword, $minutes = 60)
    {
        $value = Cache::remember('game::cacheSearchByKeywordQuery(' . strtolower($keyword) . ')', $minutes, function () use ($keyword) {
            return Game::Query()->where('bgg_name', 'like', '%' . $keyword . '%')->orderBy('bgg_name')->get();
        });
        return $value;
    }

    public function getNameAttribute()
    {
        if ($this->bgg_name) {
            return $this->bgg_name;
        }
        return $this->bgg_name;
    }

    public function getSlugAttribute()
    {
        if ($this->bgg_slug) {
            return $this->bgg_slug;
        }
        return strtolower(preg_replace("/[^0-9a-z]/i", "", $this->bgg_name));
    }


    public function getCostDiscountAttribute()
    {
        if ($this->mnmk_price > 0) {
            return $this->mnmk_price;
        }
        if ($this->mnmk_retail > 0) {
            return $this->mnmk_retail;
        }
        if ($this->dist_retail > 0 && $this->dist_retail > $this->dist_price) {
            return $this->dist_retail;
        }

        return $this->dist_price * 100 / 65;
    }

    public function getCostMsrpAttribute()
    {

        if ($this->mnmk_retail > 0) {
            return $this->mnmk_retail;
        }
        if ($this->dist_retail > 0 && $this->dist_retail > $this->dist_price) {
            return $this->dist_retail;
        }

        if ($this->dist_price > 0) {
            return $this->dist_price * 100 / 65;
        }
        return $this->mnmk_price;


    }


    public function getCostEstTotalAttribute()
    {

        return $this->cost_no_tax;
    }

    public function getCostEstMinAttribute()
    {
        return min($this->cost_simple_full_40, $this->cost_no_tax);
    }

    public function getCostEstMaxAttribute()
    {
        return max($this->cost_simple_full_40, $this->cost_no_tax);
    }


    public function getCostSimpleFull40Attribute()
    {

        if ($this->cost_msrp == 0) {
            return $this->cost_discount * 40 * 1.07;
        }
        return $this->cost_msrp * 40 * 1.07;
    }


    public function getCostDisGameAttribute()
    {
        $rate_thb = 35;
        return $this->cost_discount * $rate_thb;
    }


    public function getCostShippingAttribute()
    {
        if ($this->bgg_eswg == 0) {
            return 400;
        }
        if ($this->bgg_eswg < 1) {

            return $this->bgg_eswg * 500;
        }

        if ($this->bgg_eswg > 1 && $this->bgg_eswg < 1.5) {
            return $this->bgg_eswg * (400 + 100 * (1.5 - $this->bgg_eswg) / 0.5);
        }

        return $this->bgg_eswg * 400;

    }

    public function getCostThaiPostAttribute()
    {
        if ($this->bgg_eswg == 0) {
            return 150;
        }
        return ($this->bgg_eswg > 2 ? 200 : (($this->bgg_eswg > 1 ? 150 : (100))));

    }

    public function getCostNoTaxAttribute()
    {
        return $this->cost_dis_game + $this->cost_shipping + $this->cost_thai_post;
    }


    static function SearchBggByKeyword($keyword)
    {
        $url = "search?query=" . str_replace(" ", "+", $keyword) . "&type=boardgame,boardgameexpansion&stats=1&versions=1";
        //echo $url;

        $itemArray = self::loadBGGAPI($url, 60 * 24 * 7);

        if (!array_key_exists('item', $itemArray)) {
            return [];
        }

        $loadCollecter = array();
        //var_dump($itemArray);
        $thingItems = array();

        if (!$itemArray['item'][0]) {
            $thingItems[] = $itemArray['item'];
        } else {
            $thingItems = $itemArray['item'];
        }

        if ($thingItems) foreach ($thingItems as $item) {
            $type = $item['@attributes']['type'];
            $thing_id = $item['@attributes']['id'];
            $loadCollecter[$type][] = $thing_id;
        }

        $matchObjects = array();
        $count_match = 0;
        $count_unmatch = 0;
        foreach ($loadCollecter as $type => $list) {
            $url = "thing?id=" . implode(",", $list) . "&type=" . $type;
            $boardgameArray = self::loadBGGAPI($url, 60 * 24 * 7 * 10);
            if (!$boardgameArray['item']) continue;
//            var_dump($boardgameArray);

            $thingItems = array();
            if (!$boardgameArray['item'][0]) {
                $thingItems[] = $boardgameArray['item'];
            } else {
                $thingItems = $boardgameArray['item'];
            }
            foreach ($thingItems as $item) {
                if (!array_key_exists('thumbnail', $item)) {
//                    var_dump($item);
                }
                $row =
                    [
                        'id' => $item['@attributes']['id'],
                        'type' => $item['@attributes']['type'],
                        'name' => "",
                        'thumbnail' => "",
                        'image' => "",
                        'year' => $item['yearpublished']['@attributes']['value'],
                        //'names' => $item['name'],
                    ];

                if (array_key_exists('thumbnail', $item)) {
                    $row['thumbnail'] = $item['thumbnail'];
                }
                if (array_key_exists('thumbnail', $item)) {
                    $row['image'] = $item['image'];
                }

                if (array_key_exists('@attributes', $item['name']) && $item['name']['@attributes']['value'] != '') {
                    $row['name'] = $item['name']['@attributes']['value'];
                } else {
                    $row['name'] = $item['name'][0]['@attributes']['value'];
                }

                foreach ($item['link'] as $link) {
                    $row[$link['@attributes']['type']][] = $link['@attributes']['value'];
                }


                $matchObjects[$row['id']] = $row;

                if (strtolower(preg_replace('/[^a-zA-Z0-9]/', '', $keyword)) == strtolower(preg_replace('/[^a-zA-Z0-9]/', '', $row['name']))) {
                    $count_match++;
                    $match_id = $row['id'];
                }

                $count_unmatch++;
                $unmatch_id = $row['id'];
                //break;
            }
        }

//		var_dump($matchObjects);
        return $matchObjects;
    }


    static function loadBGGAPI($url, $minutes = 60)
    {
        $key = 'load_bgg::' . strtolower($url);
        $xml_result = Cache::remember($key, $minutes, function () use ($url) {
            $bgg_url = 'https://www.boardgamegeek.com/xmlapi2/' . $url;
            $client = new \GuzzleHttp\Client();
            $res = $client->get($bgg_url);
            $data = $res->getBody();
//            echo $data;
            return "" . $data . "";
        });

        if (strlen($xml_result) == 0) {
            Cache::forget($key);
        }

        $xml = simplexml_load_string($xml_result);
        $json = json_encode($xml);
        $retArray = json_decode($json, TRUE);
        $retArray['raw'] = $xml_result;

        return $retArray;
    }

    static function createByBGGAPI($id)
    {
        $data = self::LoadBGGPropertiesAPI($id, 'boardgame,boardgameexpansion');

//        var_dump($data);
        /*
         *   'id' => string '26713' (length=5)
          'type' => string 'boardgame' (length=9)
          'thumbnail' => string '//cf.geekdo-images.com/images/pic163426_t.jpg' (length=45)
          'image' => string '//cf.geekdo-images.com/images/pic163426.jpg' (length=43)

resources/views/games.blade.php
@extends('layouts.app')

@section('title')
    ราคากลางบอร์ดเกม อักษร {{strtoupper($active)}}
@endsection

@section('content')


    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">รายชื่อเกม</div>

                    <div class="panel-body">
                        <form action="{{url("/games/search")}}">
                            <div class="input-group col-md-6">
                                <input type="text" class="form-control" placeholder="Search for..." name="keyword"
                                       value="{{$keyword}}"/>
                                  <span class="input-group-btn">
                                    <input class="btn btn-default" type="submit" value="Go!"/>
                                  </span>

                            </div><!-- /input-group -->
                        </form>
                        <ul class="pagination">
                            <li class="{{$active=='0-9'?'active':''}}"><a href="{{url("/games-alphabet/0-9")}}">0-9 </a>
                            </li>
                            @foreach (range('a', 'z') as $char)
                                <li class="{{$active==$char?'active':''}}"><a
                                            href="{{url("/games-alphabet/".$char)}}">{{strtoupper($char)}}</a></li>
                            @endforeach
                        </ul>
                        <div class="table-responsive-disable">

                            @if (count($games)>0)
                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th>
                                            ชื่อ
                                        </th>
                                        <th class="text-right visible-md visible-lg">
                                            ราคา $
                                        </th>
                                        <th class="text-right visible-md visible-lg">
                                            ~ราคา
                                        </th>
                                        <th class="text-right visible-md visible-lg">
                                            ซื้อ/ขาย
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {{-- @var \App\Game $game --}}
                                    @foreach ($games as $game)
                                        @php
                                        $post = null;
                                        $mode = 0;
                                        if($posts){
                                        $post = $posts->where('game_id',$game->id)->last();
                                        if($post){
                                        if($post->post_type == \App\Post::POST_TYPE_BUY){
                                        $mode = 1;
                                        }
                                        if($post->post_type == \App\Post::POST_TYPE_SALE){
                                        $mode = 2;
                                        }
                                        }
                                        }
                                        @endphp
                                        <tr>
                                            <td class="name">
                                                <a class="visible-xs visible-sm big"
                                                   href="{{url("/game/".$game->bgg_id."/".$game->slug)}}">{{$game->bgg_name}}</a>
                                                <a class="visible-md visible-lg"
                                                   href="{{url("/game/".$game->bgg_id."/".$game->slug)}}">{{$game->bgg_name}}</a>

                                                <div class="visible-xs visible-sm">
                                                    <span class="big pull-right">
                                                        @if ($game->cost_est_min>0)
                                                            {{number_format($game->cost_est_min)}}
                                                            - {{number_format($game->cost_est_max)}}

                                                        @else
                                                            -
                                                        @endif
                                                        </span>
                                                <span class="big">
                                                    @if ($game->cost_msrp>0)
                                                        @if($game->mnmk_price>0)
                                                            <s>${{number_format($game->cost_msrp,2)}}</s>
                                                            <strong>${{number_format($game->mnmk_price,2)}}</strong>
                                                        @else
                                                            <strong>${{number_format($game->cost_msrp,2)}}</strong>
                                                        @endif
                                                    @else
                                                        -
                                                    @endif
                                                </span>
                                                    <div class="clearfix"></div>
                                                    <div class="pull-right">

                                                        @if (Auth::guest())
                                                            <a class="btn btn-success"
                                                               href="{{ url('/login/facebook')."?redirect=". urlencode(url()->current()) }}"
                                                               class="brn btn-facebook">ซื้อ</a>
                                                            <a class="btn btn-danger"
                                                               href="{{ url('/login/facebook')."?redirect=". urlencode(url()->current()) }}"
                                                               class="brn btn-facebook">ขาย</a>
                                                        @else
                                                            <form_post_buy ex_class="small" def_mode="{{$mode}}"
                                                                           game_id="{{$game->id}}"
                                                                           def_post_id="{{$post?$post->id:''}}"
                                                                           def_buy_init="{{floor($game->cost_est_min/100)*100}}"
                                                                           def_sell_init="{{ceil($game->cost_est_max/100)*100}}"
                                                                           def_buy_value="{{$post&&$post->post_type==\App\Post::POST_TYPE_BUY?$post->price_1:''}}"
                                                                           def_sell_value="{{$post&&$post->post_type==\App\Post::POST_TYPE_SALE?$post->price_1:''}}"
                                                            />

                                                        @endif
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>

                                            </td>
                                            <td class="text-right visible-md visible-lg">
                                                @if ($game->cost_msrp>0)

                                                    @if($game->mnmk_price>0)
                                                        <s>${{number_format($game->cost_msrp,2)}}</s>
                                                        <strong>{{number_format($game->mnmk_price,2)}}</strong>
                                                    @else
                                                        <strong>{{number_format($game->cost_msrp,2)}}</strong>
                                                    @endif
                                                @else
                                                    -
                                                @endif
                                            </td>
                                            <td class="text-right text-right visible-md visible-lg">
                                                @if ($game->cost_est_min>0)
                                                    <strong>  {{number_format($game->cost_est_min)}}
                                                        - {{number_format($game->cost_est_max)}}</strong>
                                                @else
                                                    -
                                                @endif

                                            </td>
                                            <td class="buy_sell visible-md visible-lg">

                                                @if (Auth::guest())
                                                    <a class="btn btn-success"
                                                       href="{{ url('/login/facebook')."?redirect=". urlencode(url()->current()) }}"
                                                       class="brn btn-facebook">ซื้อ</a>
                                                    <a class="btn btn-danger"
                                                       href="{{ url('/login/facebook')."?redirect=". urlencode(url()->current()) }}"
                                                       class="brn btn-facebook">ขาย</a>
                                                @else
                                                    {{--{{$post}}--}}
                                                    <form_post_buy ex_class="large" def_mode="{{$mode}}"
                                                                   game_id="{{$game->id}}"
                                                                   def_post_id="{{$post?$post->id:''}}"
                                                                   def_buy_init="{{floor($game->cost_est_min/100)*100}}"
                                                                   def_sell_init="{{ceil($game->cost_est_max/100)*100}}"
                                                                   def_buy_value="{{$post&&$post->post_type==\App\Post::POST_TYPE_BUY?$post->price_2:''}}"
                                                                   def_sell_value="{{$post&&$post->post_type==\App\Post::POST_TYPE_SALE?$post->price_2:''}}"
                                                    />
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>

                            @else
                                <div class="well text-center">
                                    ยังไม่พบเกมที่ค้นหา อาจจะเป็นเพราะเรายังไม่ได้โหลดข้อมูลมา<br/> ลองกดปุ่ม
                                    ค้นเพิ่มเติม ด้านล่างดูนะ <br/>
                                    #เด๋วมันจะโหลดมาเพิ่มเอง
                                </div>
                            @endif

                        </div>

                        @if ($keyword)

                            <div class="text-center"><a class="btn btn-primary"
                                                        href="{{url("games/search_more?keyword=".$keyword)}}">

                                    @if (count($games)>0)
                                        ยังไม่เจอเกมที่หา กดค้นเพิ่มเติม ที่นี่
                                    @else
                                        ค้นเพิ่มเติม กดที่นี่
                                    @endif
                                </a></div>
                        @else
                            #บางทีเกมที่ลีสตามอักษรอาจจะมาไม่หมด ถ้าหาไม่เจอให้กด search ด้านบนเลยนะ
                        @endif

                    </div>

                    <div class="panel-footer">* ราคา $ อ้างอิงจาก MiniatureMarket</div>
                </div>
            </div>
        </div>
    </div>



@endsection

resources/views/games_bgg.blade.php
@extends('layouts.app')

@section('content')


    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">รายชื่อเกม</div>

                    <div class="panel-body">
                        <form action="{{url("/games/search")}}">
                            <div class="input-group col-md-6">
                                <input type="text" class="form-control" placeholder="Search for..." name="keyword"
                                       value="{{$keyword}}"/>
                                  <span class="input-group-btn">
                                    <input class="btn btn-default" type="submit" value="Go!"/>
                                  </span>

                            </div><!-- /input-group -->
                        </form>
                        <ul class="pagination">
                            <li class="{{$active=='0-9'?'active':''}}"><a href="{{url("/games-alphabet/0-9")}}">0-9 </a>
                            </li>
                            @foreach (range('a', 'z') as $char)
                                <li class="{{$active==$char?'active':''}}"><a
                                            href="{{url("/games-alphabet/".$char)}}">{{strtoupper($char)}}</a></li>
                            @endforeach
                        </ul>
                        <div class="table-responsive-disable">


                            @if (count($games)>0)


                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th>
                                            ชื่อ
                                        </th>
                                        <th class="text-right">
                                            ซื้อ/ขาย
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {{-- @var \App\Game $game --}}
                                    {{--                                {{var_export($games['item'],true)}}--}}
                                    @foreach ($games as $game)
                                        <tr>

                                            <td class="name">
                                                <a class="visible-xs visible-sm big"
                                                   href="{{url("/game/".$game['id']."/".$game['name'])}}">{{$game['name']}}</a>
                                                <a class="visible-md visible-lg"
                                                   href="{{url("/game/".$game['id']."/".$game['name'])}}">{{$game['name']}}</a>

                                                {{--{{var_dump($game['id'])}}--}}
                                                {{--                                            {{var_dump($game['name'])}}--}}

                                            </td>
                                            <td>
                                                <div class="visible-xs visible-sm text-right">
                                                    <a href="{{url("/game/".$game['id']."/".$game['name'])}}"
                                                       class="btn btn-primary btn-lg">เลือก</a>
                                                </div>
                                                <div class="visible-md visible-lg text-right">
                                                    <a href="{{url("/game/".$game['id']."/".$game['name'])}}"
                                                       class="btn btn-primary">เลือก</a>
                                                </div>
                                                {{--                                            {{var_dump($game)}}--}}

                                            </td>
                                        </tr>


                                    @endforeach
                                    </tbody>
                                </table>

                            @else
                                <div class="well text-center">
                                    ไม่พบเกมที่ค้นหาเลย สะกดถูกป่าว #ผิดชัวร์
                                </div>
                            @endif

                        </div>


                    </div>

                    <div class="panel-footer">* ราคา $ อ้างอิงจาก MiniatureMarket</div>
                </div>
            </div>
        </div>
    </div>



@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/main.blade.php
@extends('layouts.app')

@section('content')
    @yield('menu')
    @yield('body')
@endsection